### ISSUE TITLE
Allow per-package logging configurations

### ISSUE THREAD

**Issue by FichteFoll** [scholer/sublime_logging_control#1]
It would be nice if this package could also set per-package logging configuration (level, format, file stuff). If all packages would use the logging module and I would set the level to DEBUG, it would become very noise very easily when I only want to debug a specific package.

From my experience, this _should_ be possible - at least for the level. Things would get complicated when packages also implement their own filters or multiple handlers.

It would also be problematic for ST2 probably because plugins are not properly structured there.

**Comment by scholer** [comment]
Hi @FichteFoll , that's a good idea as well, and certainly something we can implement rather easily. Just have a custom logger with custom log msg filter, and let the user specify a list of custom levels depending on the input. There might be a little work for the user to configure every thing right, since different packages might have different setups. E.g. some packages will have one logger for each module, using `logger = logging.getLogget(__name__)` while other packages might just issue all log messages through the root logger. In the first case, the user could do the filtering based on the logger's name; in the latter the user would have to use other parameters, e.g. the filename, for filtering.

**Comment by scholer** [comment]
This should be supported now in v1.0.2 through the use of logging.config.dictConfig. Users can use a dictionary (either external file or directly in the `.sublime-settings` file) to configure the logging system. This makes it possible to create custom loggers, filters, and handlers and connect them as-needed to get the desired behaviour. 

The "best practice" for libraries is to have loggers be named according to their package/module: `logger = logging.getLogger(__name__)`. So for example, the logger used by Logging Control is named according to its module: `logging_control.logging_control`. (The first `logging_control` being the package name and the second `logging_control` being the module `logging_control.py` inside the package.

If packages/libraries conforms to this standard, it is fairly easy to filter messages from different packages and libraries and e.g. set up a logging system that prints debug messages from only one particular library.

The feature is documented in the README, and there is an example file with even more explanation. However, reading the Python documentation for the logging library is essential to fully understand how to configure Python's logging system.

**Comment by FichteFoll** [comment]
Neat. This might finally be usable for real plugins. I'll take a look at it again when I revisit one of my plugins.
