### ISSUE TITLE
[Question] logging_file_rotating setting

### ISSUE THREAD

**Issue by Kristinita** [scholer/sublime_logging_control#4]
### 1. Briefly

What is `logging_file_rotating` setting? May you show examples of working of this setting?

### 2. Did not help

In documentation I read only

> `logging_file_rotating` can be set to true in order to use a "rotating" log-file scheme.

But what is «"rotating" log-file scheme»?

Also I try change true/false values, but I not see changes.

Thanks.

**Comment by scholer** [comment]
FIxed with the latest version:

```logging_file_rotating``` can be set to true in order to use a "rotating" log-file scheme. When the log file exceeds 20 MB it is renamed to `<logfilename>.log.1` and a new logfile is created (creating up to 3 old log files). See [Python – Logging module – RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) for more details.
